import type { WeaponCategory, WeaponDefinition, WeaponId, WeaponSlot } from '../types/game';

export const weaponCatalog: Record<WeaponId, WeaponDefinition> = {
  knife: {
    id: 'knife',
    slot: 'knife',
    category: 'knife',
    name: 'Combat Knife',
    magazineSize: 0,
    reserveAmmo: 0,
    damage: 55,
    fireCooldownSeconds: 0.42,
    reloadSeconds: 0,
  },
  glock: {
    id: 'glock',
    slot: 'secondary',
    category: 'pistol',
    name: 'Glock',
    imagePath: '/assets/pistol-glock.png',
    firstPersonImagePath: '/assets/fps-glock.png',
    magazineSize: 20,
    reserveAmmo: 80,
    damage: 24,
    fireCooldownSeconds: 0.14,
    reloadSeconds: 1.2,
  },
  usp: {
    id: 'usp',
    slot: 'secondary',
    category: 'pistol',
    name: 'USP-S',
    imagePath: '/assets/pistol-USPS.png',
    firstPersonImagePath: '/assets/fps-usps.png',
    magazineSize: 12,
    reserveAmmo: 48,
    damage: 28,
    fireCooldownSeconds: 0.18,
    reloadSeconds: 1.28,
  },
  deagle: {
    id: 'deagle',
    slot: 'secondary',
    category: 'pistol',
    name: 'Desert Eagle',
    imagePath: '/assets/pistol-dessert-eagle.png',
    magazineSize: 7,
    reserveAmmo: 35,
    damage: 52,
    fireCooldownSeconds: 0.34,
    reloadSeconds: 1.55,
  },
  m4a1: {
    id: 'm4a1',
    slot: 'primary',
    category: 'rifle',
    name: 'M4A1',
    firstPersonImagePath: '/assets/fps-M4A1.png',
    magazineSize: 30,
    reserveAmmo: 90,
    damage: 28,
    fireCooldownSeconds: 0.095,
    reloadSeconds: 1.65,
  },
  ak47: {
    id: 'ak47',
    slot: 'primary',
    category: 'rifle',
    name: 'AK-47',
    magazineSize: 30,
    reserveAmmo: 90,
    damage: 36,
    fireCooldownSeconds: 0.11,
    reloadSeconds: 1.8,
  },
  famas: {
    id: 'famas',
    slot: 'primary',
    category: 'rifle',
    name: 'FAMAS',
    magazineSize: 25,
    reserveAmmo: 75,
    damage: 26,
    fireCooldownSeconds: 0.09,
    reloadSeconds: 1.7,
  },
  galil: {
    id: 'galil',
    slot: 'primary',
    category: 'rifle',
    name: 'Galil AR',
    magazineSize: 35,
    reserveAmmo: 90,
    damage: 24,
    fireCooldownSeconds: 0.095,
    reloadSeconds: 1.72,
  },
  awp: {
    id: 'awp',
    slot: 'primary',
    category: 'rifle',
    name: 'AWP',
    magazineSize: 10,
    reserveAmmo: 30,
    damage: 100,
    fireCooldownSeconds: 1.15,
    reloadSeconds: 2.25,
  },
  flashbang: {
    id: 'flashbang',
    slot: 'knife',
    category: 'grenade',
    name: 'Flashbang',
    magazineSize: 1,
    reserveAmmo: 0,
    damage: 0,
    fireCooldownSeconds: 0.8,
    reloadSeconds: 0,
  },
  smoke: {
    id: 'smoke',
    slot: 'knife',
    category: 'grenade',
    name: 'Smoke Grenade',
    magazineSize: 1,
    reserveAmmo: 0,
    damage: 0,
    fireCooldownSeconds: 0.8,
    reloadSeconds: 0,
  },
  frag: {
    id: 'frag',
    slot: 'knife',
    category: 'grenade',
    name: 'Frag Grenade',
    magazineSize: 1,
    reserveAmmo: 0,
    damage: 85,
    fireCooldownSeconds: 0.8,
    reloadSeconds: 0,
  },
};

export const weaponsByCategory: Record<Exclude<WeaponCategory, 'knife'>, WeaponId[]> = {
  pistol: ['glock', 'usp', 'deagle'],
  rifle: ['m4a1', 'ak47', 'famas', 'galil', 'awp'],
  grenade: ['flashbang', 'smoke', 'frag'],
};

export const defaultWeaponForSlot: Record<WeaponSlot, WeaponId> = {
  primary: 'm4a1',
  secondary: 'glock',
  knife: 'knife',
};

export const getWeapon = (weaponId: WeaponId): WeaponDefinition => weaponCatalog[weaponId];
